package automation.modules.cards;

import automation.core.AssertHelper;
import automation.core.Config;
import automation.core.api.ApiDetails;
import automation.modules.access.AuthHelper;
import automation.modules.access.web.DashboardPage;
import automation.modules.cards.api.CardApi;
import automation.modules.cards.web.CardListPage;
import automation.modules.cards.web.CardPage;

/**
 * High-level helper for common card workflows.
 * Extends AuthHelper so it inherits login (doLogin, loginAndSetAuth) and all API methods.
 *
 * Web usage:
 *   CardHelper cards = new CardHelper(config);
 *   DashboardPage dashboard = cards.doLogin(user);
 *   CardPage cardPage = cards.createCardViaUI(dashboard, card);
 *
 * API usage:
 *   CardHelper cards = new CardHelper(config);
 *   cards.loginAndSetAuth(user);
 *   CardData created = cards.createCard(card);
 */
public class CardHelper extends AuthHelper
{

    public CardHelper(Config config)
    {
        super(config);
    }

    // ========== API WORKFLOWS ==========

    public CardData createCard(CardData card)
    {
        CardData created = executeAndVerify(CardApi.CreateCard, card, card);
        AssertHelper.assertNotNull(config, created.getId(), "Card ID generated by server");
        return created;
    }

    public CardData getCard(String cardId)
    {
        ApiDetails endpoint = CardApi.GetCard.withPath("id", cardId);
        return execute(endpoint, null, CardData.class);
    }

    public CardData updateCard(String cardId, CardData updates)
    {
        ApiDetails endpoint = CardApi.UpdateCard.withPath("id", cardId);
        return executeAndVerify(endpoint, updates, updates);
    }

    public void deleteCard(String cardId)
    {
        ApiDetails endpoint = CardApi.DeleteCard.withPath("id", cardId);
        execute(endpoint);
    }

    // ========== WEB WORKFLOWS ==========

    public CardPage createCardViaUI(DashboardPage dashboard, CardData card)
    {
        CardListPage cardList = dashboard.navigateToCards();
        CardPage cardPage = cardList.clickCreateCard();
        cardPage.createCard(card);
        return cardPage;
    }

    public CardListPage navigateToCards(DashboardPage dashboard)
    {
        return dashboard.navigateToCards();
    }
}
