Browser=chromium
Environment=test
DebugMode=false
ObjectWaitTime=25
EndExecutionOnFailure=true
RemoteExecution=false
Headless=false
SlowMo=0
ViewportWidth=1920
ViewportHeight=1080
# VideoMode options: on, off, retain-on-failure
VideoMode=retain-on-failure