# Default Configuration
environment=staging
browser=chromium
headless=true
projectName=CustomerFrontend
country=sg
appLanguage=en
ObjectWaitTime=30
VideoMode=on_failure
slowMo=
endExecutionOnFailure=false
debugMode=true
# GitHub
githubUrl=https://github.com/

db.thanos.url=jdbc:mysql://<host>:3306/<dbname>
db.thanos.username=<username>
db.thanos.password=<password>