# Default Configuration
environment=staging
browser=chromium
headless=false
projectName=CustomerFrontend
country=sg
appLanguage=en
ObjectWaitTime=30
VideoMode=on_failure
slowMo=
endExecutionOnFailure=false
debugMode=true