#DB Connection
db.automation.url=jdbc:mysql://127.0.0.1:3306/thanos
db.automation.username=root
db.automation.password=
# GitHub
githubUrl=https://github.com/
github.username=automationdemo@yopmail.com
github.password=automationPassword
# SauceDemo
saucedemo.url=https://www.saucedemo.com/
saucedemo.username=standard_user
saucedemo.password=secret_sauce